export default {
  'app.title': 'Nicemail',
  'app.shortTitle': 'Nicemail',

  // Navigation / folders
  'nav.inbox': 'Inbox',
  'nav.starred': 'Starred',
  'nav.drafts': 'Drafts',
  'nav.sent': 'Sent',
  'nav.trash': 'Trash',
  'nav.archive': 'Archive',
  'nav.junk': 'Junk',
  'nav.all': 'All Mail',
  'nav.folders': 'Folders',
  'nav.settings': 'Settings',
  'nav.addAccount': 'Add account',
  'nav.accounts': 'Accounts',

  // Actions
  'action.compose': 'New mail',
  'action.refresh': 'Sync',
  'action.send': 'Send',
  'action.saveDraft': 'Save draft',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'action.confirm': 'OK',
  'action.reply': 'Reply',
  'action.replyAll': 'Reply all',
  'action.forward': 'Forward',
  'action.download': 'Download',
  'action.add': 'Add',
  'action.remove': 'Remove',
  'action.close': 'Close',
  'action.back': 'Back',
  'action.settings': 'Settings',
  'action.loading': 'Loading…',
  'action.syncing': 'Syncing…',
  'action.addAttachment': 'Add attachment',

  // Empty states
  'empty.noAccounts': 'No accounts yet',
  'empty.noAccountsHint': 'Add your first email account to get started',
  'empty.noMessages': 'No messages here',
  'empty.noSearchResults': 'No messages found',
  'empty.selectMessage': 'Select a message to read',
  'empty.welcome': 'Welcome to Nicemail',
  'empty.welcomeHint': 'Add an email account to view and send messages',

  // Account wizard
  'wizard.title': 'Add account',
  'wizard.provider': 'Choose a provider',
  'wizard.preset163': '163 Mail',
  'wizard.preset126': '126 Mail',
  'wizard.presetQQ': 'QQ Mail',
  'wizard.presetGmail': 'Gmail',
  'wizard.presetOutlook': 'Outlook / Microsoft',
  'wizard.presetCustom': 'Custom IMAP/SMTP',
  'wizard.name': 'Display name',
  'wizard.namePlaceholder': 'Your name (shown to recipients)',
  'wizard.email': 'Email address',
  'wizard.emailPlaceholder': 'name@example.com',
  'wizard.password': 'Password / app password',
  'wizard.password163': 'Authorization code',
  'wizard.passwordPlaceholder': 'Enable IMAP/SMTP on the web client to obtain it',
  'wizard.authCodeHint163': 'Enable POP3/SMTP/IMAP under Settings and generate an authorization code.',
  'wizard.authCodeHintQQ': 'Enable the service under Settings → Account and generate an authorization code.',
  'wizard.authCodeHintGmail': 'Click the button below to sign in with your Google account.',
  'wizard.authCodeHintOutlook': 'Click the button below to sign in with your Microsoft account.',
  'wizard.oauthLogin': 'Sign in with {provider}',
  'wizard.oauthNotConfigured': 'OAuth client credentials not configured',
  'wizard.oauthNotConfiguredHint': 'Fill in the Google/Azure client ID in config first (see the OAuth guide)',
  'wizard.customImap': 'IMAP server',
  'wizard.customImapPlaceholder': 'imap.example.com',
  'wizard.customPort': 'Port',
  'wizard.customSmtp': 'SMTP server',
  'wizard.customSmtpPlaceholder': 'smtp.example.com',
  'wizard.ssl': 'Use SSL/TLS',
  'wizard.testing': 'Testing…',
  'wizard.testConnection': 'Test connection',
  'wizard.test': 'Test & add',
  'wizard.testFailed': 'Connection failed: {message}',
  'wizard.testSuccess': 'Connected, account added',
  'wizard.required': 'Please fill in the required fields',
  'wizard.invalidEmail': 'Email format is invalid',
  'wizard.oauthTitle': 'Finishing sign-in…',
  'wizard.oauthWait': 'Return to this window after you finish signing in',

  // Message list
  'mail.unread': 'Unread',
  'mail.noSubject': '(no subject)',
  'mail.yesterday': 'Yesterday',
  'mail.attachment': 'Attachment',
  'mail.from': 'From',
  'mail.to': 'To',
  'mail.cc': 'Cc',
  'mail.bcc': 'Bcc',
  'mail.subject': 'Subject',
  'mail.date': 'Date',
  'mail.body': 'Body',
  'mail.showRemote': 'Show remote images',
  'mail.remoteBlocked': 'Remote images blocked',
  'mail.loadRemote': 'Load images',
  'mail.downloadAttachment': 'Save attachment',
  'mail.attachments': 'Attachments ({count})',
  'mail.noBody': 'This message has no content',
  'mail.forwardSubject': 'Fwd: {subject}',
  'mail.replySubject': 'Re: {subject}',

  // Compose
  'compose.title': 'New message',
  'compose.to': 'To',
  'compose.cc': 'Cc',
  'compose.bcc': 'Bcc',
  'compose.subject': 'Subject',
  'compose.body': 'Message',
  'compose.sending': 'Sending…',
  'compose.noRecipients': 'Please enter at least one recipient',
  'compose.sent': 'Sent',
  'compose.sendFailed': 'Failed to send: {message}',
  'compose.draftSaved': 'Draft saved',
  'compose.draftFailed': 'Failed to save draft: {message}',
  'compose.fromAccount': 'From',
  'compose.addCc': 'Add Cc',
  'compose.addBcc': 'Add Bcc',

  // Search
  'search.placeholder': 'Search mail…',
  'search.allAccounts': 'All accounts',
  'search.in': 'Search in {folder}',

  // Settings
  'settings.title': 'Settings',
  'settings.appearance': 'Appearance',
  'settings.theme': 'Theme',
  'settings.light': 'Light',
  'settings.dark': 'Dark',
  'settings.system': 'System',
  'settings.material': 'Background material',
  'settings.mica': 'Mica',
  'settings.acrylic': 'Acrylic',
  'settings.accounts': 'Accounts',
  'settings.accountDelete': 'Remove account',
  'settings.accountDeleteConfirm': 'Remove account {email} and its local cache?',
  'settings.about': 'About',
  'settings.aboutVersion': 'Nicemail v{version}',
  'settings.aboutDesc': 'A third-party email client built with Tauri, Vue and WinUI styles.',
  'settings.pollInterval': 'Auto sync interval',
  'settings.pollManual': 'Manual only',
  'settings.oauthDocs': 'OAuth setup guide',
  'settings.customProvider': 'Custom mail server',

  // Status
  'status.success': 'Success',
  'status.error': 'Error',
  'status.warning': 'Warning',
  'status.info': 'Info',
  'status.authFailed': 'Authentication failed. Check your password or app password',
  'status.connectionFailed': 'Cannot connect to server: {message}',
  'status.offline': 'Offline',

  // Misc
  'folder.unread': '{count} unread',
};
