export default {
  'app.title': 'Nicemail',
  'app.shortTitle': 'Nicemail',

  // 导航 / 文件夹
  'nav.inbox': '收件箱',
  'nav.starred': '星标邮件',
  'nav.drafts': '草稿',
  'nav.sent': '已发送',
  'nav.trash': '已删除',
  'nav.archive': '归档',
  'nav.junk': '垃圾邮件',
  'nav.all': '全部邮件',
  'nav.folders': '文件夹',
  'nav.settings': '设置',
  'nav.addAccount': '添加账号',
  'nav.accounts': '账号',

  // 常用动作
  'action.compose': '写信',
  'action.refresh': '同步',
  'action.send': '发送',
  'action.saveDraft': '存草稿',
  'action.cancel': '取消',
  'action.delete': '删除',
  'action.confirm': '确定',
  'action.reply': '回复',
  'action.replyAll': '全部回复',
  'action.forward': '转发',
  'action.download': '下载',
  'action.add': '添加',
  'action.remove': '移除',
  'action.close': '关闭',
  'action.back': '返回',
  'action.settings': '设置',
  'action.loading': '加载中…',
  'action.syncing': '正在同步…',
  'action.addAttachment': '添加附件',

  // 空状态
  'empty.noAccounts': '还没有账号',
  'empty.noAccountsHint': '添加你的第一个邮箱账号开始使用',
  'empty.noMessages': '这里没有邮件',
  'empty.noSearchResults': '没有找到匹配的邮件',
  'empty.selectMessage': '选择一封邮件开始阅读',
  'empty.welcome': '欢迎使用 Nicemail',
  'empty.welcomeHint': '添加邮箱账号,查看和发送邮件',

  // 账号向导
  'wizard.title': '添加账号',
  'wizard.provider': '选择邮箱服务商',
  'wizard.preset163': '163 邮箱',
  'wizard.preset126': '126 邮箱',
  'wizard.presetQQ': 'QQ 邮箱',
  'wizard.presetGmail': 'Gmail',
  'wizard.presetOutlook': 'Outlook / Microsoft',
  'wizard.presetCustom': '自定义 IMAP/SMTP',
  'wizard.name': '显示名称',
  'wizard.namePlaceholder': '你的名字(收件人看到的名字)',
  'wizard.email': '邮箱地址',
  'wizard.emailPlaceholder': 'name@example.com',
  'wizard.password': '密码 / 授权码',
  'wizard.password163': '授权码',
  'wizard.passwordPlaceholder': '在邮箱网页端开启 IMAP/SMTP 后获取',
  'wizard.authCodeHint163': '需在网页端「设置 → POP3/SMTP/IMAP」开启服务并获取授权码。',
  'wizard.authCodeHintQQ': '需在网页端「设置 → 账户 → 开启服务」生成授权码。',
  'wizard.authCodeHintGmail': '点击下方按钮,使用 Google 账号授权登录。',
  'wizard.authCodeHintOutlook': '点击下方按钮,使用 Microsoft 账号授权登录。',
  'wizard.oauthLogin': '使用 {provider} 授权登录',
  'wizard.oauthNotConfigured': '未配置 OAuth 客户端凭据',
  'wizard.oauthNotConfiguredHint': '请先在 config 中填入 Google/Azure 客户端 ID(见 OAuth 申请文档)',
  'wizard.customImap': 'IMAP 服务器',
  'wizard.customImapPlaceholder': 'imap.example.com',
  'wizard.customPort': '端口',
  'wizard.customSmtp': 'SMTP 服务器',
  'wizard.customSmtpPlaceholder': 'smtp.example.com',
  'wizard.ssl': '使用 SSL/TLS',
  'wizard.testing': '正在验证…',
  'wizard.testConnection': '测试连接',
  'wizard.test': '验证并添加',
  'wizard.testFailed': '连接失败:{message}',
  'wizard.testSuccess': '连接成功,账号已添加',
  'wizard.required': '请填写必填项',
  'wizard.invalidEmail': '邮箱格式不正确',
  'wizard.oauthTitle': '正在完成授权…',
  'wizard.oauthWait': '授权完成后请回到本窗口',

  // 邮件列表
  'mail.unread': '未读',
  'mail.noSubject': '(无主题)',
  'mail.yesterday': '昨天',
  'mail.attachment': '附件',
  'mail.from': '发件人',
  'mail.to': '收件人',
  'mail.cc': '抄送',
  'mail.bcc': '密送',
  'mail.subject': '主题',
  'mail.date': '日期',
  'mail.body': '正文',
  'mail.showRemote': '显示远程图片',
  'mail.remoteBlocked': '已阻止远程图片',
  'mail.loadRemote': '加载图片',
  'mail.downloadAttachment': '保存附件',
  'mail.attachments': '附件 ({count})',
  'mail.noBody': '这封邮件没有内容',
  'mail.forwardSubject': '转发:{subject}',
  'mail.replySubject': '回复:{subject}',

  // 写信
  'compose.title': '写邮件',
  'compose.to': '收件人',
  'compose.cc': '抄送',
  'compose.bcc': '密送',
  'compose.subject': '主题',
  'compose.body': '正文',
  'compose.sending': '正在发送…',
  'compose.noRecipients': '请至少填写一个收件人',
  'compose.sent': '已发送',
  'compose.sendFailed': '发送失败:{message}',
  'compose.draftSaved': '草稿已保存',
  'compose.draftFailed': '草稿保存失败:{message}',
  'compose.fromAccount': '发件账号',
  'compose.addCc': '添加抄送',
  'compose.addBcc': '添加密送',

  // 搜索
  'search.placeholder': '搜索邮件…',
  'search.allAccounts': '全部账号',
  'search.in': '在 {folder} 中搜索',

  // 设置
  'settings.title': '设置',
  'settings.appearance': '外观',
  'settings.theme': '主题',
  'settings.light': '浅色',
  'settings.dark': '深色',
  'settings.system': '跟随系统',
  'settings.material': '背景材质',
  'settings.mica': 'Mica',
  'settings.acrylic': 'Acrylic',
  'settings.accounts': '账号',
  'settings.accountDelete': '删除账号',
  'settings.accountDeleteConfirm': '确定删除账号 {email} 及其本地缓存?',
  'settings.about': '关于',
  'settings.aboutVersion': 'Nicemail v{version}',
  'settings.aboutDesc': '基于 Tauri + Vue + WinUI 风格的第三方邮件客户端。',
  'settings.pollInterval': '自动同步间隔',
  'settings.pollManual': '仅手动',
  'settings.oauthDocs': 'OAuth 申请文档',
  'settings.customProvider': '自定义邮箱',

  // 通用状态
  'status.success': '成功',
  'status.error': '错误',
  'status.warning': '警告',
  'status.info': '信息',
  'status.authFailed': '认证失败,请检查密码或授权码',
  'status.connectionFailed': '无法连接服务器:{message}',
  'status.offline': '离线',

  // 分类
  'folder.unread': '{count} 封未读',
};
